// 한국 공휴일 정적 데이터
// scripts/update-holidays.mjs 가 자동 생성 (최종 갱신: 2026-04-30)
// 소스: Google Calendar "대한민국의 휴일" 공개 iCal 피드
// 수동 보정이 필요하면 스크립트 재실행 대신 이 파일을 직접 수정 후 재배포.

export const HOLIDAYS = {
  2023: [
    { month:  1, day:  1, name: "새해첫날" },
    { month:  1, day: 21, name: "설날 연휴" },
    { month:  1, day: 22, name: "설날" },
    { month:  1, day: 23, name: "설날 연휴" },
    { month:  1, day: 24, name: "설날 연휴" },
    { month:  3, day:  1, name: "삼일절" },
    { month:  5, day:  5, name: "어린이날" },
    { month:  5, day: 27, name: "부처님오신날" },
    { month:  5, day: 29, name: "석가탄신일 대체공휴일" },
    { month:  6, day:  6, name: "현충일" },
    { month:  8, day: 15, name: "광복절" },
    { month:  9, day: 28, name: "추석 연휴" },
    { month:  9, day: 29, name: "추석" },
    { month:  9, day: 30, name: "추석 연휴" },
    { month: 10, day:  2, name: "추석 (대체공휴일)" },
    { month: 10, day:  3, name: "개천절" },
    { month: 10, day:  9, name: "한글날" },
    { month: 12, day: 25, name: "크리스마스" },
  ],
  2024: [
    { month:  1, day:  1, name: "새해첫날" },
    { month:  2, day:  9, name: "설날 연휴" },
    { month:  2, day: 10, name: "설날" },
    { month:  2, day: 11, name: "설날 연휴" },
    { month:  2, day: 12, name: "설날 연휴" },
    { month:  3, day:  1, name: "삼일절" },
    { month:  4, day: 10, name: "국회의원선거일" },
    { month:  5, day:  5, name: "어린이날" },
    { month:  5, day:  6, name: "어린이날 대체공휴일" },
    { month:  5, day: 15, name: "부처님오신날" },
    { month:  6, day:  6, name: "현충일" },
    { month:  8, day: 15, name: "광복절" },
    { month:  9, day: 17, name: "추석" },
    { month:  9, day: 18, name: "추석 연휴" },
    { month: 10, day:  1, name: "국군의날" },
    { month: 10, day:  3, name: "개천절" },
    { month: 10, day:  9, name: "한글날" },
    { month: 12, day: 25, name: "크리스마스" },
  ],
  2025: [
    { month:  1, day:  1, name: "새해첫날" },
    { month:  1, day: 27, name: "설날 연휴" },
    { month:  1, day: 28, name: "설날 연휴" },
    { month:  1, day: 29, name: "설날" },
    { month:  1, day: 30, name: "설날 연휴" },
    { month:  3, day:  1, name: "삼일절" },
    { month:  3, day:  3, name: "삼일절 대체공휴일" },
    { month:  5, day:  5, name: "부처님오신날·어린이날" },
    { month:  5, day:  6, name: "어린이날 대체공휴일" },
    { month:  6, day:  3, name: "대통령 선거" },
    { month:  6, day:  6, name: "현충일" },
    { month:  8, day: 15, name: "광복절" },
    { month: 10, day:  3, name: "개천절" },
    { month: 10, day:  5, name: "추석 연휴" },
    { month: 10, day:  6, name: "추석" },
    { month: 10, day:  7, name: "추석 연휴" },
    { month: 10, day:  8, name: "추석 연휴 대체공휴일" },
    { month: 10, day:  9, name: "한글날" },
    { month: 12, day: 25, name: "크리스마스" },
  ],
  2026: [
    { month:  1, day:  1, name: "새해첫날" },
    { month:  2, day: 16, name: "설날 연휴" },
    { month:  2, day: 17, name: "설날" },
    { month:  2, day: 18, name: "설날 연휴" },
    { month:  3, day:  1, name: "삼일절" },
    { month:  3, day:  2, name: "삼일절 대체공휴일" },
    { month:  5, day:  1, name: "노동절" },
    { month:  5, day:  5, name: "어린이날" },
    { month:  5, day: 24, name: "부처님오신날" },
    { month:  5, day: 25, name: "부처님오신날 대체공휴일" },
    { month:  6, day:  3, name: "지방선거일" },
    { month:  6, day:  6, name: "현충일" },
    { month:  7, day: 17, name: "제헌절" },
    { month:  8, day: 15, name: "광복절" },
    { month:  8, day: 17, name: "광복절 대체공휴일" },
    { month:  9, day: 24, name: "추석 연휴" },
    { month:  9, day: 25, name: "추석" },
    { month:  9, day: 26, name: "추석 연휴" },
    { month: 10, day:  3, name: "개천절" },
    { month: 10, day:  5, name: "개천절 대체공휴일" },
    { month: 10, day:  9, name: "한글날" },
    { month: 12, day: 25, name: "크리스마스" },
  ],
  2027: [
    { month:  1, day:  1, name: "새해첫날" },
    { month:  2, day:  6, name: "설날" },
    { month:  2, day:  8, name: "설날 연휴" },
    { month:  3, day:  1, name: "삼일절" },
    { month:  5, day:  1, name: "노동절" },
    { month:  5, day:  3, name: "노동절 대체공휴일" },
    { month:  5, day:  5, name: "어린이날" },
    { month:  5, day: 13, name: "부처님오신날" },
    { month:  6, day:  6, name: "현충일" },
    { month:  7, day: 17, name: "제헌절" },
    { month:  8, day: 15, name: "광복절" },
    { month:  9, day: 14, name: "추석 연휴" },
    { month:  9, day: 15, name: "추석" },
    { month:  9, day: 16, name: "추석 연휴" },
    { month: 10, day:  3, name: "개천절" },
    { month: 10, day:  9, name: "한글날" },
    { month: 10, day: 11, name: "한글날 대체공휴일" },
    { month: 12, day: 25, name: "크리스마스" },
  ],
  2028: [
    { month:  1, day:  1, name: "새해첫날" },
    { month:  1, day: 26, name: "설날" },
    { month:  1, day: 27, name: "설날 연휴" },
    { month:  3, day:  1, name: "삼일절" },
    { month:  5, day:  1, name: "노동절" },
    { month:  5, day:  2, name: "부처님오신날" },
    { month:  5, day:  5, name: "어린이날" },
    { month:  6, day:  6, name: "현충일" },
    { month:  7, day: 17, name: "제헌절" },
    { month:  8, day: 15, name: "광복절" },
    { month: 10, day:  2, name: "추석 연휴" },
    { month: 10, day:  3, name: "개천절·추석" },
    { month: 10, day:  4, name: "추석 연휴" },
    { month: 10, day:  9, name: "한글날" },
    { month: 12, day: 25, name: "크리스마스" },
  ],
  2029: [
    { month:  1, day:  1, name: "새해첫날" },
    { month:  2, day: 13, name: "설날" },
    { month:  2, day: 14, name: "설날 연휴" },
    { month:  3, day:  1, name: "삼일절" },
    { month:  5, day:  1, name: "노동절" },
    { month:  5, day:  5, name: "어린이날" },
    { month:  5, day: 20, name: "부처님오신날" },
    { month:  5, day: 21, name: "부처님오신날 대체공휴일" },
    { month:  6, day:  6, name: "현충일" },
    { month:  7, day: 17, name: "제헌절" },
    { month:  8, day: 15, name: "광복절" },
    { month:  9, day: 21, name: "추석 연휴" },
    { month:  9, day: 22, name: "추석" },
    { month:  9, day: 23, name: "추석 연휴" },
    { month:  9, day: 24, name: "추석 연휴 대체공휴일" },
    { month: 10, day:  3, name: "개천절" },
    { month: 10, day:  9, name: "한글날" },
    { month: 12, day: 25, name: "크리스마스" },
  ],
  2030: [
    { month:  1, day:  1, name: "새해첫날" },
    { month:  2, day:  4, name: "설날·설날 연휴" },
    { month:  3, day:  1, name: "삼일절" },
    { month:  5, day:  1, name: "노동절" },
    { month:  5, day:  5, name: "어린이날" },
    { month:  5, day:  9, name: "부처님오신날" },
    { month:  6, day:  6, name: "현충일" },
    { month:  7, day: 17, name: "제헌절" },
    { month:  8, day: 15, name: "광복절" },
    { month:  9, day: 11, name: "추석 연휴" },
    { month:  9, day: 12, name: "추석" },
    { month:  9, day: 13, name: "추석 연휴" },
    { month: 10, day:  3, name: "개천절" },
    { month: 10, day:  9, name: "한글날" },
    { month: 12, day: 25, name: "크리스마스" },
  ],
  2031: [
    { month:  1, day:  1, name: "새해첫날" },
    { month:  1, day: 23, name: "설날" },
    { month:  1, day: 24, name: "설날 연휴" },
    { month:  3, day:  1, name: "삼일절" },
    { month:  3, day:  3, name: "삼일절 대체공휴일" },
    { month:  5, day:  1, name: "노동절" },
    { month:  5, day:  5, name: "어린이날" },
    { month:  5, day: 28, name: "부처님오신날" },
    { month:  6, day:  6, name: "현충일" },
    { month:  7, day: 17, name: "제헌절" },
    { month:  8, day: 15, name: "광복절" },
    { month:  9, day: 30, name: "추석 연휴" },
    { month: 10, day:  1, name: "추석" },
    { month: 10, day:  2, name: "추석 연휴" },
    { month: 10, day:  3, name: "개천절" },
    { month: 10, day:  9, name: "한글날" },
    { month: 12, day: 25, name: "크리스마스" },
  ],
}
